<h1><center>Practical: Markov Chains</center></h1>

<h2>Assignment 3 - PageRank </h2>

In this assignment, the aim is to implement the PageRank algorithm, and analyze the effect of teleporting factor on the output of the algorithm.

### Importing necessary packages

In [1]:
# if you have already installed numpy and matplotlib, you can skip the next two lines
!pip install matplotlib
!pip install numpy

import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
# constructing the connectivity matrix
A = np.array([[1,1,0],[1,0,1],[0,0,1]])

## Implementing the elements of the PageRank algorithm


In order to perform the algorithm, we define the following functions:
- normalize_conn_matrix: computing the transition probability from the connecting matrix,
- appr_stationary: compute the stationary distribution, based on x(t) = x(t-1) . T,
- dead_end: to prevent dead end problem,
- teleporting_factor: to resolve spider trap, 

Hint. you may use "np.matmul" function for the matrix multiplication.

In [26]:
def normalize_conn_matrix(A):
    """
    A: (n*n) connectivity matrix
    T: transition probabilities
    """
    # Insert your code here
    n = A.shape[0]
    T = np.zeros((n,n))

    # Calculate probability for each row
    probs = 1/A.sum(axis=1)

    # Create transition probabilities
    T = np.transpose(np.transpose(A)*probs)
    
    return T

normalize_conn_matrix(np.array([[1,0],[1,1]]))

array([[1. , 0. ],
       [0.5, 0.5]])

In [27]:
# Test your code
T = normalize_conn_matrix(A)
print(T)

print("\n Expected solution:")
print("[[0.5 0.5 0. ] \n [0.5 0.  0.5] \n  [0.  0.  1. ]]")

[[0.5 0.5 0. ]
 [0.5 0.  0.5]
 [0.  0.  1. ]]

 Expected solution:
[[0.5 0.5 0. ] 
 [0.5 0.  0.5] 
  [0.  0.  1. ]]


In [45]:
def appr_stationary(T, maxiter=20):
    """
    Lukke
    T: transition probability,
    maxiter: number of steps
    x_m: the state vector
    """
    n = len(T[0])
    x = [[1/n] * n]
    for i in range(1, maxiter+1):
        x.append(np.matmul(x[i-1], T))
    x_m = x[maxiter]
    return x_m

In [46]:
# Test your code
st_dist = appr_stationary(T, maxiter=20)
print(st_dist)

print("\n Expected solution:")
print("[[0.00430107 0.00265821 0.99304072]]")


[0.00563018 0.00347964 0.99089019]

 Expected solution:
[[0.00430107 0.00265821 0.99304072]]


In [ ]:
def dead_end(A):
    """
    A: connecting matrix
    A_new: connecting matrix by resolving the dead end problem
    """
    # Insert your code here
    
    
    
    return A_new

In [ ]:
print(dead_end(A))

print("\n Expected output:")
print("[[1 1 0] \n [1 0 1] \n [0 0 1]]")

In [47]:
def teleporting_factor(T, alpha=0.9):
    """
    Lukke
    T: transition probability,
    alpha: teleporting factor.
    T_new: transition probability after implementing teleporting factor
    """
    
    # Insert your code here
    n = len(T[0])
    T_new = np.zeros((n,n))
    for r in range(n):
        for c in range(n):
            T_new[r][c] = alpha*T[r][c] + ((1-alpha) * (1/n))
    return T_new

In [48]:
print(teleporting_factor(T))

print("\n Expected output:")
print("[[0.48333333 0.48333333 0.03333333] \n [0.48333333 0.03333333 0.48333333] \n [0.03333333 0.03333333 0.93333333]]")

[[0.48333333 0.48333333 0.03333333]
 [0.48333333 0.03333333 0.48333333]
 [0.03333333 0.03333333 0.93333333]]

 Expected output:
[[0.48333333 0.48333333 0.03333333] 
 [0.48333333 0.03333333 0.48333333] 
 [0.03333333 0.03333333 0.93333333]]


## PageRank algorithm 

Here, we use the functions, defined above, to perform PageRank algorithm.
   1) resolve the dead end problem,<br>
   2) compute the transition probability, <br>
   3) use teleporting factor to prevent spider trap,<br>
   4) compute the stationary distribuion.<br>

In [ ]:
def PageRank(A, alpha=0.8, maxiter=20):
    """
    Lukke
    A: connectivity matrix,
    alpha: teleporting factor,
    maxiter: number of steps (for approximating stationary distribution)
    st_dist: an approximation for the stationary distribution 
    """
    
    # Insert your code here
    
    
    
    return st_dist

In [ ]:
print(PageRank(A, 0.9, 30))

print("\n Expected output:")
print("[[0.13910008 0.09593028 0.76496964]]")

<h1><center>Analyzing PageRank algorithm</center></h1>

<h2>Performing PageRank algorithm on the following network </h2>

![Cat](graph.png)

In the following, please perform:

- Performing PageRank algorithm on the network,
- Investigating the effect of teleporting 

### 1) Perform PageRank algorithm

Apply PageRank on the network (alpha = 0.85), and report the pageranks,
   1) Construct the connectivity matrix, <br>
   2) Apply PageRank algorithm (i.e. function "PageRank")

In [ ]:
# Insert your code here



### 2) The effect of spider trap

In order to see the effect of spider trap on the output, please perform PageRank algorithm with different alpha values. <br>
Run the algorithm with alpha = 1 (corresponding to not using the teleporting factor):<br>
    - compare its output with alpha = 0.85, <br>
    - please discuss the effect of teleporting factor on the stationary distribution. 
    

In [ ]:
# Insert your code here




Write at the top of the first page of your report: “Introduction to Scientific Computing, Practical Markov Chains”, followed by your names, student numbers, and the date when you hand in the report.

Since you work in pairs, you need to include information in your report about your individual contributions. For each assignment, indicate the contribution (mention percentages) for each of you in terms of tasks performed (program design, program implementation, answering questions posed, writing the report). All files have to be handed in as a single archive (called YourName.zip), where “YourName” is the concatenation of your last names. See Nestor for the address to which you have to send the archive.